"""
ado-workflows: Azure DevOps workflow automation library.

Three-layer API for Azure DevOps operations:
- Layer 1 — Primitives: pure functions (URL parsing, git inspection, date parsing)
- Layer 2 — Context: stateful caching (RepositoryContext, thread-safe)
- Layer 3 — PR Context: composed workflows (AzureDevOpsPRContext)
"""

from __future__ import annotations

from ado_workflows.auth import AZURE_DEVOPS_RESOURCE_ID, ConnectionFactory, get_current_user
from ado_workflows.client import AdoClient
from ado_workflows.comments import (
    analyze_pr_comments,
    post_comment,
    post_comments,
    post_rich_comments,
    reply_to_comment,
    resolve_comments,
    sanitize_ado_response,
)
from ado_workflows.content import list_repo_items
from ado_workflows.context import (
    RepositoryContext,
    clear_repository_context,
    discover_all_repositories,
    get_context_status,
    get_repository_context,
    set_repository_context,
)
from ado_workflows.discovery import (
    discover_repositories,
    infer_target_repository,
    inspect_git_repository,
)
from ado_workflows.errors import classify_ado_error
from ado_workflows.formatting import (
    CommentFormatter,
    default_comment_formatter,
    format_comment,
)
from ado_workflows.lifecycle import (
    abandon_pull_request,
    add_label,
    add_reviewer,
    complete_pull_request,
    create_pull_request,
    get_pr_work_item_refs,
    get_pull_request,
    link_work_items_to_pr,
    list_labels,
    list_reviewers,
    remove_label,
    remove_reviewer,
    retarget_pull_request,
    set_draft_status,
    update_pull_request,
)
from ado_workflows.listing import (
    get_work_item,
    get_work_items,
    list_commits,
    list_pull_requests,
    query_work_items,
)
from ado_workflows.models import (
    VOTE_TEXT,
    ApprovalStatus,
    AuthorSample,
    CommentAnalysis,
    CommentInfo,
    CommentPayload,
    CommentSeverity,
    CommentSummary,
    CommentType,
    CommitSummary,
    ContentResult,
    CreatedPR,
    FileChange,
    FileContent,
    IterationContext,
    IterationInfo,
    LabelDetail,
    MergeStrategy,
    PendingPR,
    PendingReviewResult,
    PostedCommentDetail,
    PostingResult,
    PullRequestDetail,
    PullRequestSummary,
    RepoItem,
    ResolveResult,
    ReviewerDetail,
    ReviewerInfo,
    ReviewStatus,
    RichComment,
    RichPostingResult,
    UserIdentity,
    VoteStatus,
    WorkItemDetail,
    WorkItemFieldInfo,
    WorkItemRef,
    WorkItemSummary,
)
from ado_workflows.mutations import (
    clone_work_item,
    create_work_item,
    get_work_item_type_fields,
    move_work_items_to_sprint,
    update_work_item,
)
from ado_workflows.parsing import parse_ado_date, parse_ado_url, parse_ado_work_item_url
from ado_workflows.pr import AzureDevOpsPRContext, establish_pr_context, get_pr_author
from ado_workflows.praise import filter_self_praise, is_praise_comment
from ado_workflows.review import (
    analyze_pending_reviews,
    fetch_required_approvals,
    fetch_vote_timestamps,
    get_review_status,
)
from ado_workflows.votes import deduplicate_team_containers, determine_vote_status
from ado_workflows.work_items import (
    AzureDevOpsWorkItemContext,
    establish_work_item_context,
)

__all__: list[str] = [
    "AZURE_DEVOPS_RESOURCE_ID",
    "VOTE_TEXT",
    "AdoClient",
    "ApprovalStatus",
    "AuthorSample",
    "AzureDevOpsPRContext",
    "AzureDevOpsWorkItemContext",
    "CommentAnalysis",
    "CommentFormatter",
    "CommentInfo",
    "CommentPayload",
    "CommentSeverity",
    "CommentSummary",
    "CommentType",
    "CommitSummary",
    "ConnectionFactory",
    "ContentResult",
    "CreatedPR",
    "FileChange",
    "FileContent",
    "IterationContext",
    "IterationInfo",
    "LabelDetail",
    "MergeStrategy",
    "PendingPR",
    "PendingReviewResult",
    "PostedCommentDetail",
    "PostingResult",
    "PullRequestDetail",
    "PullRequestSummary",
    "RepoItem",
    "RepositoryContext",
    "ResolveResult",
    "ReviewStatus",
    "ReviewerDetail",
    "ReviewerInfo",
    "RichComment",
    "RichPostingResult",
    "UserIdentity",
    "VoteStatus",
    "WorkItemDetail",
    "WorkItemFieldInfo",
    "WorkItemRef",
    "WorkItemSummary",
    "abandon_pull_request",
    "add_label",
    "add_reviewer",
    "analyze_pending_reviews",
    "analyze_pr_comments",
    "classify_ado_error",
    "clear_repository_context",
    "clone_work_item",
    "complete_pull_request",
    "create_pull_request",
    "create_work_item",
    "deduplicate_team_containers",
    "default_comment_formatter",
    "determine_vote_status",
    "discover_all_repositories",
    "discover_repositories",
    "establish_pr_context",
    "establish_work_item_context",
    "fetch_required_approvals",
    "fetch_vote_timestamps",
    "filter_self_praise",
    "format_comment",
    "get_context_status",
    "get_current_user",
    "get_pr_author",
    "get_pr_work_item_refs",
    "get_pull_request",
    "get_repository_context",
    "get_review_status",
    "get_work_item",
    "get_work_item_type_fields",
    "get_work_items",
    "infer_target_repository",
    "inspect_git_repository",
    "is_praise_comment",
    "link_work_items_to_pr",
    "list_commits",
    "list_labels",
    "list_pull_requests",
    "list_repo_items",
    "list_reviewers",
    "move_work_items_to_sprint",
    "parse_ado_date",
    "parse_ado_url",
    "parse_ado_work_item_url",
    "post_comment",
    "post_comments",
    "post_rich_comments",
    "query_work_items",
    "remove_label",
    "remove_reviewer",
    "reply_to_comment",
    "resolve_comments",
    "retarget_pull_request",
    "sanitize_ado_response",
    "set_draft_status",
    "set_repository_context",
    "update_pull_request",
    "update_work_item",
]
